all: reg1and2 reg3 cache3

reg1and2:reg1and2.c
	gcc -o reg1and2 reg1and2.c -lm

reg3:reg3.c
	gcc -o reg3 reg3.c -lm

cache3:cache3.c
	gcc -o cache3 cache3.c -lm

clean:
	-rm -f reg1and2.o reg3.o cache3.o
